services:
  # ==========================================
  # 1. POSTIZ APP (DEV)
  # ==========================================
  postiz-app-dev:
    container_name: postiz-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: localhost/postiz-app-dev:latest
    restart: unless-stopped
    ports:
      - "4201:4200" 
      - "5001:5000"
      - "3001:3000"
    env_file:
      - ./.dev
    depends_on:
      postiz-postgres-dev:
        condition: service_healthy
      postiz-redis-dev:
        condition: service_healthy
    networks:
      - postiz-network-dev
#      - postiz-network
    volumes:
      - ./:/app
      - ./.dev:/app/.env:ro
      - ./uploads:/app/uploads

  # ==========================================
  # 2. DATABASE (DEV)
  # ==========================================
  postiz-postgres-dev:
    image: postgres:17-alpine
    container_name: postiz-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postiz-user
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_DB: postiz-db-dev # שם DB שונה ליתר ביטחון
    volumes:
      - postiz_postgres_data_dev:/var/lib/postgresql/data # ווליום נפרד לחלוטין!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postiz-user -d postiz-db-dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postiz-network-dev

  # ==========================================
  # 3. REDIS (DEV)
  # ==========================================
  postiz-redis-dev:
    image: redis:7.2-alpine
    container_name: postiz-redis-dev
    restart: unless-stopped
    volumes:
      - postiz_redis_data_dev:/data # ווליום נפרד
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postiz-network-dev

networks:
  postiz-network-dev:
    driver: bridge

# postiz-network:
#    external: true


volumes:
  postiz_postgres_data_dev:
  postiz_redis_data_dev:
